model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm1D_v1.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: gt_image
    cond_stage_key: cond_image
    image_size: 256
    channels: 256
    conditioning_key: crossattn
    cond_stage_trainable: true
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel1D_v1.UNetModel
      params:
        image_size: 64
        in_channels: 256
        out_channels: 256
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder1D_v1.VQModel
      params:
        ckpt_path: models/first_stage_models/vq-f4/abp.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.models.autoencoder1D_v1.VQModel
      params:
        # ckpt_path: models/first_stage_models/vq-f4/ppg.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: ldm.data.ppg2abp.PPG2ABPDataset_v3_Train
      params:
        size: 256
    validation:
      target: ldm.data.ppg2abp.PPG2ABPDataset_v3_Val
      params:
        size: 256
