model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder1D_v1.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 1 # self.post_quant_conv = torch.nn.Conv1d(embed_dim, ddconfig["z_channels"], 1)
    image_key: gt_image
    ddconfig:
      double_z: True
      z_channels: 1
      resolution: 1152
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: ldm.modules.losses.contperceptual.LPIPSWithDiscriminator_2
      params:
        disc_start: 20001
        kl_weight: 0.01
        disc_weight: 0.5


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: ldm.data.ppg2abp.PPG2ABPDataset_v3_Train
      params:
        data_len: -1
        size: 256
        data_root: "..\\..\\data\\processed\\BP_npy\\250107_1152f_corr\\p00"
    validation:
      target: ldm.data.ppg2abp.PPG2ABPDataset_v3_Val
      params:
        size: 256
        data_root: "..\\..\\data\\processed\\BP_npy\\250107_1152f_corr\\p00"

lightning:
  callbacks:
    image_logger:
      target: main.FigLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False
  trainer:
    gpus: 0,
    benchmark: True
    accumulate_grad_batches: 2